### ISSUE TITLE
Fixing branches that have non trunk `copy-from-path`

### ISSUE THREAD

**Issue by dten** [eduardosm/svn2git#49]
Hey thanks for the help earlier. Don't hurry to this 😆

I hinted at weird branches and was going to look at if perhaps there was a way to add some new options to achieve a nice git repo. I made a test file (love how easy this was!) that hopefully demonstrates the issue. 

I'm 90% certain git2svn can't currently do this with existing config options, but was wondering if you thought there was anything that would make this very difficult to implement.

```yaml
svn-revs:
  - props:
      svn:log: init trunk
    nodes:
      - path: trunk
        kind: dir
        action: add
      - path: trunk/x
        kind: dir
        action: add
      - path: trunk/x/f
        kind: file
        action: add
        text: "file f\n"
  - props:
      svn:log: branch from trunk/x
    nodes:
      - path: branches/b1
        kind: dir
        action: add
        copy-from-path: trunk/x
  - props:
      svn:log: modify file in branch
    nodes:
      - path: branches/b1/f
        kind: file
        action: change
        text: "modified f\n"
  - props:
      svn:log: merge b1:3 into trunk
    nodes:
      - path: trunk/x
        kind: dir
        action: change
        props:
          svn:mergeinfo: |
            /branches/b1:3
      - path: trunk/x/f
        kind: file
        action: change
        text: "modified f\n"

conv-params: |
  branches = ["trunk", "branches/b1"]

# This is what happens
git-revs:
  - rev: trunk
    parents: [trunk~1]
    tree:
      x:
        type: dir
      x/f:
        type: normal
        data: "modified f\n"
  - rev: branches/b1
    parents: [branches/b1~1]
    tree:
      f:
        type: normal
        data: "modified f\n"
  - rev: branches/b1~1
    parents: []
    tree:
      f:
        type: normal
        data: "file f\n"
  - rev: trunk~1
    parents: []
    tree:
      x:
        type: dir
      x/f:
        type: normal
        data: "file f\n"

# This is what I wished happened
git-revs:
  - rev: trunk
    parents: [trunk~1, branches/b1]
    tree:
      x:
        type: dir
      x/f:
        type: normal
        data: "modified f\n"
  - rev: branches/b1
    parents: [branches/b1~1]
    tree:
      x:
        type: dir
      x/f:
        type: normal
        data: "modified f\n"
  - rev: branches/b1~1
    parents: [trunk~1]
    tree:
      x:
        type: dir
      x/f:
        type: normal
        data: "file f\n"
  - rev: trunk~1
    parents: []
    tree:
      x:
        type: dir
      x/f:
        type: normal
        data: "file f\n"
```

**Comment by dten** [comment]
i looked into the dates winding back and it is what the svn log says, so i guess it's all fine

**Comment by eduardosm** [comment]
Great! I will merge https://github.com/eduardosm/svn2git/pull/53 and try to figure out how to handle merges.

**Comment by eduardosm** [comment]
I pushed an initial implementation of support for merges to the [partial-branches](https://github.com/eduardosm/svn2git/tree/partial-branches) branch. For now, it is experimental and there are still some corner cases that might need to be handled.

**Comment by dten** [comment]
Oo exiting. I'll give it a try shortly

**Comment by dten** [comment]
hmm maybe not, i made a test for that case and it passes fine

```
svn-revs:
  - props:
      svn:log: init directories
    nodes:
      - path: trunk
        kind: dir
        action: add
      - path: branches
        kind: dir
        action: add
  - props:
      svn:log: init trunk
    nodes:
      - path: trunk/x
        kind: dir
        action: add
      - path: trunk/x/A
        kind: file
        action: add
        text: "file A\n"
  - props:
      svn:log: copy trunk/x to branches/b1
    nodes:
      - path: branches/b1
        kind: dir
        action: add
        copy-from-path: trunk/x
  - props:
      svn:log: init trunk
    nodes:
      - path: trunk/y
        kind: dir
        action: add
      - path: trunk/y/B
        kind: file
        action: add
        text: "file B\n"
  - no: 5
    props:
      svn:log: modify A
    nodes:
      - path: branches/b1/A
        kind: file
        action: change
        text: "modified A\n"
  - props:
      svn:log: merge b1:5 into trunk
    nodes:
      - path: trunk/x
        kind: dir
        action: change
        props:
          svn:mergeinfo: |
            /branches/b1:5
      - path: trunk/x/A
        kind: file
        action: change
        text: "modified A\n"

conv-params: |
  branches = [
    "trunk",
    "branches/*",
  ]
  rename-branches."trunk" = "master"
  rename-branches."branches/*" = "*"

  partial-branches = [
    "branches/*",
  ]

logs: |
  D svn2git::convert::stage1: importing SVN revision 3
  D svn2git::convert::stage1: creating partial branch/tag "branches/b1" from "trunk" with sub-path "x"
  D svn2git::convert::stage2: emitting branch commits and tags for SVN revision 5
  D svn2git::convert::stage2: candidate to be merged: "branches/b1"@5
  D svn2git::convert::stage2: merging into "trunk"

git-revs:
  - rev: master~3
    parents: []
    tree: {}
  - rev: master~1
    parents: [master~2]
    tree:
      x:
        type: dir
      x/A:
        type: normal
        data: "file A\n"
      y:
        type: dir
      y/B:
        type: normal
        data: "file B\n"
  - rev: master~0
    parents: [master~1, b1~0]
    tree:
      x:
        type: dir
      x/A:
        type: normal
        data: "modified A\n"
      y:
        type: dir
      y/B:
        type: normal
        data: "file B\n"
  - rev: b1~1
    parents: [master~2]
    tree:
      x:
        type: dir
      x/A:
        type: normal
        data: "file A\n"
  - rev: b1~0
    parents: [b1~1]
    tree:
      x:
        type: dir
      x/A:
        type: normal
        data: "modified A\n"
```
